<#include "/WEB-INF/view/common/bizTag/loanLimit.ftl" />
<#include "/WEB-INF/view/common/bizTag/loanStatus.ftl" />
<#include "/WEB-INF/view/common/bizTag/loanType.ftl" />
<#include "/WEB-INF/view/common/bizTag/menuLevel.ftl" />
<#include "/WEB-INF/view/common/bizTag/pageType.ftl" />
<#include "/WEB-INF/view/common/bizTag/enumValue.ftl" />
<#include "/WEB-INF/view/common/bizTag/loanStatusButton.ftl" />
<#include "/WEB-INF/view/common/bizTag/handleStatus.ftl" />
<#include "/WEB-INF/view/common/bizTag/loanInterestManner.ftl" />
<#include "/WEB-INF/view/common/bizTag/message.ftl" />
<#include "/WEB-INF/view/common/bizTag/approveType.ftl" />
