<#include "${commonResultPath}/common/control/text.ftl" />
<#include "${commonResultPath}/common/control/datepicker.ftl" />
<#include "${commonResultPath}/common/control/dropdownlist.ftl" />
<#include "${commonResultPath}/common/control/textarea.ftl" />
<#include "${commonResultPath}/common/control/editor.ftl" />
<#include "${commonResultPath}/common/control/radioButtonList.ftl" />
<#include "${commonResultPath}/common/control/linkButton.ftl" />
<#include "${commonResultPath}/common/control/button.ftl" />
<#include "${commonResultPath}/common/control/password.ftl" />
<#include "${commonResultPath}/common/control/checkBoxList.ftl" />
<#include "${commonResultPath}/common/control/tr.ftl" />
<#include "${commonResultPath}/common/control/page.ftl" />
<#include "${commonResultPath}/common/control/pageAjax.ftl" />
<#include "${commonResultPath}/common/control/error.ftl" />
<#include "${commonResultPath}/common/control/imgUpload.ftl" />
<#include "${commonResultPath}/common/control/fileUpload.ftl" />
<#include "${commonResultPath}/common/control/verifyCode.ftl" />
<#include "${commonResultPath}/common/control/token.ftl" />